import React  from "react";
import { scaleLinear, max } from "d3";

// Render a histogram 
//   bins is a data structure generated by d3 histogram()
export default function renderHistogram({bins, margins, histSize}) {
    // const yScaleMax = graph.edges.length;
    const yScaleMax = max(bins.map(b => b.length));
    const yScale = scaleLinear()
        .domain([0, yScaleMax])
        .range([0, histSize.height]);
    const xScale = scaleLinear()
        .domain([0, 1])
        .range([0, histSize.width]);
    const xTicks = xScale.ticks(5);
    const yTicks = yScale.ticks(5),
        yFormat = yScale.tickFormat(5, "s");

    const svgWidth = margins.left + margins.right + histSize.width + 22;
    const svgHeight = margins.left + margins.right + histSize.height + 10;

    return (
        <svg width={svgWidth} height={svgHeight}>
            <g transform={`translate(${margins.left + 22},${margins.top})`} className="histogram">
                {bins.map((bin, i) => (
                    <rect
                        className="bar"
                        key={i}
                        x={xScale(bin.x0)}
                        y={histSize.height - yScale(bin.length)}
                        width={xScale(bin.x1 - bin.x0) - 1}
                        height={yScale(bin.length)}
                    />
                ))}

                <g className="axis" transform={`translate(0,${histSize.height})`}>
                    <line x1={0} y1={0} x2={histSize.width} y2={0} />
                    {xTicks.map((x, i) => (
                        <text key={i} x={xScale(x)} y={10} textAnchor="middle">
                            {x}
                        </text>
                    ))}
                </g>
                <g className="axis">
                    <line x1={0} y1={histSize.height} x2={0} y2={0} />
                    {yTicks.map((y, i) => (
                        <text key={i} x={-6} y={histSize.height - yScale(y)} textAnchor="end">
                            {yFormat(y)}
                        </text>
                    ))}
                </g>
            </g>
        </svg>
    );
}
